<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Clube extends \AppBundle\Entity\Clube implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'ID_Clube', 'Nome', 'Abrv', 'N_FPF', 'Associacao', 'Fundacao', 'Presidente', 'Estadio', 'Cidade', 'Pais', 'Foto'];
        }

        return ['__isInitialized__', 'ID_Clube', 'Nome', 'Abrv', 'N_FPF', 'Associacao', 'Fundacao', 'Presidente', 'Estadio', 'Cidade', 'Pais', 'Foto'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Clube $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIDClube()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIDClube', []);

        return parent::getIDClube();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbrv($abrv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbrv', [$abrv]);

        return parent::setAbrv($abrv);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbrv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbrv', []);

        return parent::getAbrv();
    }

    /**
     * {@inheritDoc}
     */
    public function setNFPF($nFPF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNFPF', [$nFPF]);

        return parent::setNFPF($nFPF);
    }

    /**
     * {@inheritDoc}
     */
    public function getNFPF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNFPF', []);

        return parent::getNFPF();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssociacao($associacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssociacao', [$associacao]);

        return parent::setAssociacao($associacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssociacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssociacao', []);

        return parent::getAssociacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFundacao($fundacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFundacao', [$fundacao]);

        return parent::setFundacao($fundacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFundacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFundacao', []);

        return parent::getFundacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setPresidente($presidente)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPresidente', [$presidente]);

        return parent::setPresidente($presidente);
    }

    /**
     * {@inheritDoc}
     */
    public function getPresidente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPresidente', []);

        return parent::getPresidente();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadio($estadio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadio', [$estadio]);

        return parent::setEstadio($estadio);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadio', []);

        return parent::getEstadio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', [$cidade]);

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', []);

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFoto($foto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFoto', [$foto]);

        return parent::setFoto($foto);
    }

    /**
     * {@inheritDoc}
     */
    public function getFoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFoto', []);

        return parent::getFoto();
    }

}
