<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Entidade extends \AppBundle\Entity\Entidade implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'ID_Entidade', 'nLicenca', 'Nome', 'TipoEnt', 'Estado', 'Equipamento', 'PosicaoPreferida', 'Morada', 'Telf', 'Telm', 'Email', 'DataNasc', 'Naturalidade', 'Pais', 'CC', 'NIF', 'GSanguineo', 'Habilitacoes', 'Doencas', 'Profissao', 'UltimaAtualizacao', 'FotoInscricao', 'Inscricao', 'FotoCromos', 'Modalidades', 'EquipasJogo', 'JogadorStats', 'EscaloesResp', 'documentos', 'modosPagamentoEntidade'];
        }

        return ['__isInitialized__', 'ID_Entidade', 'nLicenca', 'Nome', 'TipoEnt', 'Estado', 'Equipamento', 'PosicaoPreferida', 'Morada', 'Telf', 'Telm', 'Email', 'DataNasc', 'Naturalidade', 'Pais', 'CC', 'NIF', 'GSanguineo', 'Habilitacoes', 'Doencas', 'Profissao', 'UltimaAtualizacao', 'FotoInscricao', 'Inscricao', 'FotoCromos', 'Modalidades', 'EquipasJogo', 'JogadorStats', 'EscaloesResp', 'documentos', 'modosPagamentoEntidade'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Entidade $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIDEntidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIDEntidade', []);

        return parent::getIDEntidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNLicenca($nLicenca)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNLicenca', [$nLicenca]);

        return parent::setNLicenca($nLicenca);
    }

    /**
     * {@inheritDoc}
     */
    public function getNLicenca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNLicenca', []);

        return parent::getNLicenca();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelf($telf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelf', [$telf]);

        return parent::setTelf($telf);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelf', []);

        return parent::getTelf();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelm($telm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelm', [$telm]);

        return parent::setTelm($telm);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelm', []);

        return parent::getTelm();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataNasc($dataNasc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataNasc', [$dataNasc]);

        return parent::setDataNasc($dataNasc);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataNasc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataNasc', []);

        return parent::getDataNasc();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaturalidade($naturalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaturalidade', [$naturalidade]);

        return parent::setNaturalidade($naturalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaturalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaturalidade', []);

        return parent::getNaturalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setPais($pais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPais', [$pais]);

        return parent::setPais($pais);
    }

    /**
     * {@inheritDoc}
     */
    public function getPais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPais', []);

        return parent::getPais();
    }

    /**
     * {@inheritDoc}
     */
    public function setCC($cC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCC', [$cC]);

        return parent::setCC($cC);
    }

    /**
     * {@inheritDoc}
     */
    public function getCC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCC', []);

        return parent::getCC();
    }

    /**
     * {@inheritDoc}
     */
    public function setNIF($nIF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNIF', [$nIF]);

        return parent::setNIF($nIF);
    }

    /**
     * {@inheritDoc}
     */
    public function getNIF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNIF', []);

        return parent::getNIF();
    }

    /**
     * {@inheritDoc}
     */
    public function setGSanguineo($gSanguineo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGSanguineo', [$gSanguineo]);

        return parent::setGSanguineo($gSanguineo);
    }

    /**
     * {@inheritDoc}
     */
    public function getGSanguineo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGSanguineo', []);

        return parent::getGSanguineo();
    }

    /**
     * {@inheritDoc}
     */
    public function setHabilitacoes($habilitacoes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHabilitacoes', [$habilitacoes]);

        return parent::setHabilitacoes($habilitacoes);
    }

    /**
     * {@inheritDoc}
     */
    public function getHabilitacoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHabilitacoes', []);

        return parent::getHabilitacoes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoencas($doencas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoencas', [$doencas]);

        return parent::setDoencas($doencas);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoencas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoencas', []);

        return parent::getDoencas();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfissao($profissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfissao', [$profissao]);

        return parent::setProfissao($profissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfissao', []);

        return parent::getProfissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setUltimaAtualizacao($ultimaAtualizacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUltimaAtualizacao', [$ultimaAtualizacao]);

        return parent::setUltimaAtualizacao($ultimaAtualizacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getUltimaAtualizacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUltimaAtualizacao', []);

        return parent::getUltimaAtualizacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotoInscricao($fotoInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotoInscricao', [$fotoInscricao]);

        return parent::setFotoInscricao($fotoInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotoInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotoInscricao', []);

        return parent::getFotoInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setFotoCromos($fotoCromos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFotoCromos', [$fotoCromos]);

        return parent::setFotoCromos($fotoCromos);
    }

    /**
     * {@inheritDoc}
     */
    public function getFotoCromos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFotoCromos', []);

        return parent::getFotoCromos();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipoEnt(\AppBundle\Entity\TipoEntidade $tipoEnt = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipoEnt', [$tipoEnt]);

        return parent::setTipoEnt($tipoEnt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipoEnt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipoEnt', []);

        return parent::getTipoEnt();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipamento(\AppBundle\Entity\Equipamento $equipamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipamento', [$equipamento]);

        return parent::setEquipamento($equipamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipamento', []);

        return parent::getEquipamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscalao(\AppBundle\Entity\Escalao $escalao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscalao', [$escalao]);

        return parent::setEscalao($escalao);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscalao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscalao', []);

        return parent::getEscalao();
    }

    /**
     * {@inheritDoc}
     */
    public function setMorada(\AppBundle\Entity\Morada $morada = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMorada', [$morada]);

        return parent::setMorada($morada);
    }

    /**
     * {@inheritDoc}
     */
    public function getMorada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMorada', []);

        return parent::getMorada();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscricao(\AppBundle\Entity\DadosInscricao $inscricao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscricao', [$inscricao]);

        return parent::setInscricao($inscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscricao', []);

        return parent::getInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function addModalidade(\AppBundle\Entity\Modalidade $modalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addModalidade', [$modalidade]);

        return parent::addModalidade($modalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function removeModalidade(\AppBundle\Entity\Modalidade $modalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeModalidade', [$modalidade]);

        return parent::removeModalidade($modalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getModalidades()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModalidades', []);

        return parent::getModalidades();
    }

    /**
     * {@inheritDoc}
     */
    public function addEquipasJogo(\AppBundle\Entity\EquipaJogo $equipasJogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEquipasJogo', [$equipasJogo]);

        return parent::addEquipasJogo($equipasJogo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEquipasJogo(\AppBundle\Entity\EquipaJogo $equipasJogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEquipasJogo', [$equipasJogo]);

        return parent::removeEquipasJogo($equipasJogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipasJogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipasJogo', []);

        return parent::getEquipasJogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosicaoPreferida(\AppBundle\Entity\Posicao $posicaoPreferida = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosicaoPreferida', [$posicaoPreferida]);

        return parent::setPosicaoPreferida($posicaoPreferida);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosicaoPreferida()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosicaoPreferida', []);

        return parent::getPosicaoPreferida();
    }

    /**
     * {@inheritDoc}
     */
    public function addEscaloesResp(\AppBundle\Entity\Escalao $escaloesResp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEscaloesResp', [$escaloesResp]);

        return parent::addEscaloesResp($escaloesResp);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEscaloesResp(\AppBundle\Entity\Escalao $escaloesResp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEscaloesResp', [$escaloesResp]);

        return parent::removeEscaloesResp($escaloesResp);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscaloesResp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscaloesResp', []);

        return parent::getEscaloesResp();
    }

    /**
     * {@inheritDoc}
     */
    public function addJogadorEstatistica(\AppBundle\Entity\JogadorEstatistica $jogadorEstatistica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJogadorEstatistica', [$jogadorEstatistica]);

        return parent::addJogadorEstatistica($jogadorEstatistica);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJogadorEstatistica(\AppBundle\Entity\JogadorEstatistica $jogadorEstatistica)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJogadorEstatistica', [$jogadorEstatistica]);

        return parent::removeJogadorEstatistica($jogadorEstatistica);
    }

    /**
     * {@inheritDoc}
     */
    public function getJogadorEstatistica()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJogadorEstatistica', []);

        return parent::getJogadorEstatistica();
    }

    /**
     * {@inheritDoc}
     */
    public function addJogadorStat(\AppBundle\Entity\JogadorEstatistica $jogadorStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJogadorStat', [$jogadorStat]);

        return parent::addJogadorStat($jogadorStat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJogadorStat(\AppBundle\Entity\JogadorEstatistica $jogadorStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJogadorStat', [$jogadorStat]);

        return parent::removeJogadorStat($jogadorStat);
    }

    /**
     * {@inheritDoc}
     */
    public function getJogadorStats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJogadorStats', []);

        return parent::getJogadorStats();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocumento(\AppBundle\Entity\DocumentoEntidade $documentoEntidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocumento', [$documentoEntidade]);

        return parent::addDocumento($documentoEntidade);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocumento(\AppBundle\Entity\DocumentoEntidade $documentoEntidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocumento', [$documentoEntidade]);

        return parent::removeDocumento($documentoEntidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentos', []);

        return parent::getDocumentos();
    }

    /**
     * {@inheritDoc}
     */
    public function addModoPagamentoEntidade(\AppBundle\Entity\ModoPagamentoEntidade $mpe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addModoPagamentoEntidade', [$mpe]);

        return parent::addModoPagamentoEntidade($mpe);
    }

    /**
     * {@inheritDoc}
     */
    public function removeModoPagamentoEntidade(\AppBundle\Entity\ModoPagamentoEntidade $mpe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeModoPagamentoEntidade', [$mpe]);

        return parent::removeModoPagamentoEntidade($mpe);
    }

    /**
     * {@inheritDoc}
     */
    public function getModosPagamentoEntidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModosPagamentoEntidade', []);

        return parent::getModosPagamentoEntidade();
    }

}
