<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Jornada extends \AppBundle\Entity\Jornada implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'ID_Jornada', 'Nome', 'EquipaCasa', 'EquipaVisitante', 'LocalJogo', 'DataJogo', 'HoraJogo', 'LocalConcentracao', 'HoraConcentracao', 'GolosCasa', 'GolosVisit', 'Duracao', 'EquipasJogo', '' . "\0" . 'AppBundle\\Entity\\Jornada' . "\0" . 'JogadorStats', 'Campeonato'];
        }

        return ['__isInitialized__', 'ID_Jornada', 'Nome', 'EquipaCasa', 'EquipaVisitante', 'LocalJogo', 'DataJogo', 'HoraJogo', 'LocalConcentracao', 'HoraConcentracao', 'GolosCasa', 'GolosVisit', 'Duracao', 'EquipasJogo', '' . "\0" . 'AppBundle\\Entity\\Jornada' . "\0" . 'JogadorStats', 'Campeonato'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Jornada $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIDJornada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIDJornada', []);

        return parent::getIDJornada();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalJogo($localJogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalJogo', [$localJogo]);

        return parent::setLocalJogo($localJogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalJogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalJogo', []);

        return parent::getLocalJogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataJogo($dataJogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataJogo', [$dataJogo]);

        return parent::setDataJogo($dataJogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataJogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataJogo', []);

        return parent::getDataJogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraJogo($horaJogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraJogo', [$horaJogo]);

        return parent::setHoraJogo($horaJogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraJogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraJogo', []);

        return parent::getHoraJogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalConcentracao($localConcentracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalConcentracao', [$localConcentracao]);

        return parent::setLocalConcentracao($localConcentracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalConcentracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalConcentracao', []);

        return parent::getLocalConcentracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setHoraConcentracao($horaConcentracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHoraConcentracao', [$horaConcentracao]);

        return parent::setHoraConcentracao($horaConcentracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getHoraConcentracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHoraConcentracao', []);

        return parent::getHoraConcentracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setGolosCasa($golosCasa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGolosCasa', [$golosCasa]);

        return parent::setGolosCasa($golosCasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getGolosCasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGolosCasa', []);

        return parent::getGolosCasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setGolosVisit($golosVisit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGolosVisit', [$golosVisit]);

        return parent::setGolosVisit($golosVisit);
    }

    /**
     * {@inheritDoc}
     */
    public function getGolosVisit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGolosVisit', []);

        return parent::getGolosVisit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracao($duracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracao', [$duracao]);

        return parent::setDuracao($duracao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracao', []);

        return parent::getDuracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipaCasa(\AppBundle\Entity\Clube $equipaCasa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipaCasa', [$equipaCasa]);

        return parent::setEquipaCasa($equipaCasa);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipaCasa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipaCasa', []);

        return parent::getEquipaCasa();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipaVisitante(\AppBundle\Entity\Clube $equipaVisitante = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipaVisitante', [$equipaVisitante]);

        return parent::setEquipaVisitante($equipaVisitante);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipaVisitante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipaVisitante', []);

        return parent::getEquipaVisitante();
    }

    /**
     * {@inheritDoc}
     */
    public function addEquipasJogo(\AppBundle\Entity\EquipaJogo $equipasJogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEquipasJogo', [$equipasJogo]);

        return parent::addEquipasJogo($equipasJogo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEquipasJogo(\AppBundle\Entity\EquipaJogo $equipasJogo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEquipasJogo', [$equipasJogo]);

        return parent::removeEquipasJogo($equipasJogo);
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipasJogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipasJogo', []);

        return parent::getEquipasJogo();
    }

    /**
     * {@inheritDoc}
     */
    public function addJogadorStat(\AppBundle\Entity\JogadorEstatistica $jogadorStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJogadorStat', [$jogadorStat]);

        return parent::addJogadorStat($jogadorStat);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJogadorStat(\AppBundle\Entity\JogadorEstatistica $jogadorStat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJogadorStat', [$jogadorStat]);

        return parent::removeJogadorStat($jogadorStat);
    }

    /**
     * {@inheritDoc}
     */
    public function getJogadorStats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJogadorStats', []);

        return parent::getJogadorStats();
    }

    /**
     * {@inheritDoc}
     */
    public function addCampeonato(\AppBundle\Entity\Campeonato $campeonato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCampeonato', [$campeonato]);

        return parent::addCampeonato($campeonato);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCampeonato(\AppBundle\Entity\Campeonato $campeonato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCampeonato', [$campeonato]);

        return parent::removeCampeonato($campeonato);
    }

    /**
     * {@inheritDoc}
     */
    public function getCampeonato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampeonato', []);

        return parent::getCampeonato();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setCampeonato(\AppBundle\Entity\Campeonato $campeonato = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampeonato', [$campeonato]);

        return parent::setCampeonato($campeonato);
    }

}
