<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class DadosInscricao extends \AppBundle\Entity\DadosInscricao implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'ID_dadosInscricao', 'ExameMedico', 'FichaInscricao', 'CopiaCC', 'DataValidadeCC', 'CopiaCCEncarregado', 'DataValidadeCCEncarregado', 'FichaInscricaoFPF'];
        }

        return ['__isInitialized__', 'ID_dadosInscricao', 'ExameMedico', 'FichaInscricao', 'CopiaCC', 'DataValidadeCC', 'CopiaCCEncarregado', 'DataValidadeCCEncarregado', 'FichaInscricaoFPF'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (DadosInscricao $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIDDadosInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIDDadosInscricao', []);

        return parent::getIDDadosInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setExameMedico($exameMedico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExameMedico', [$exameMedico]);

        return parent::setExameMedico($exameMedico);
    }

    /**
     * {@inheritDoc}
     */
    public function getExameMedico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExameMedico', []);

        return parent::getExameMedico();
    }

    /**
     * {@inheritDoc}
     */
    public function setFichaInscricao($fichaInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichaInscricao', [$fichaInscricao]);

        return parent::setFichaInscricao($fichaInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichaInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichaInscricao', []);

        return parent::getFichaInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCopiaCC($copiaCC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCopiaCC', [$copiaCC]);

        return parent::setCopiaCC($copiaCC);
    }

    /**
     * {@inheritDoc}
     */
    public function getCopiaCC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCopiaCC', []);

        return parent::getCopiaCC();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataValidadeCC($dataValidadeCC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataValidadeCC', [$dataValidadeCC]);

        return parent::setDataValidadeCC($dataValidadeCC);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataValidadeCC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataValidadeCC', []);

        return parent::getDataValidadeCC();
    }

    /**
     * {@inheritDoc}
     */
    public function setCopiaCCEncarregado($copiaCCEncarregado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCopiaCCEncarregado', [$copiaCCEncarregado]);

        return parent::setCopiaCCEncarregado($copiaCCEncarregado);
    }

    /**
     * {@inheritDoc}
     */
    public function getCopiaCCEncarregado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCopiaCCEncarregado', []);

        return parent::getCopiaCCEncarregado();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataValidadeCCEncarregado($dataValidadeCCEncarregado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataValidadeCCEncarregado', [$dataValidadeCCEncarregado]);

        return parent::setDataValidadeCCEncarregado($dataValidadeCCEncarregado);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataValidadeCCEncarregado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataValidadeCCEncarregado', []);

        return parent::getDataValidadeCCEncarregado();
    }

    /**
     * {@inheritDoc}
     */
    public function setFichaInscricaoFPF($fichaInscricaoFPF)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFichaInscricaoFPF', [$fichaInscricaoFPF]);

        return parent::setFichaInscricaoFPF($fichaInscricaoFPF);
    }

    /**
     * {@inheritDoc}
     */
    public function getFichaInscricaoFPF()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFichaInscricaoFPF', []);

        return parent::getFichaInscricaoFPF();
    }

}
