<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Campeonato extends \AppBundle\Entity\Campeonato implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'ID_Campeonato', 'Escalao', 'Nome', 'DataInicial', 'DataFinal', 'Epoca', 'QtEquipas', 'Clubes', 'Jornadas'];
        }

        return ['__isInitialized__', 'ID_Campeonato', 'Escalao', 'Nome', 'DataInicial', 'DataFinal', 'Epoca', 'QtEquipas', 'Clubes', 'Jornadas'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Campeonato $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIDCampeonato()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIDCampeonato', []);

        return parent::getIDCampeonato();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataInicial($dataInicial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataInicial', [$dataInicial]);

        return parent::setDataInicial($dataInicial);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataInicial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataInicial', []);

        return parent::getDataInicial();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataFinal($dataFinal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataFinal', [$dataFinal]);

        return parent::setDataFinal($dataFinal);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataFinal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataFinal', []);

        return parent::getDataFinal();
    }

    /**
     * {@inheritDoc}
     */
    public function setQtEquipas($qtEquipas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQtEquipas', [$qtEquipas]);

        return parent::setQtEquipas($qtEquipas);
    }

    /**
     * {@inheritDoc}
     */
    public function getQtEquipas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQtEquipas', []);

        return parent::getQtEquipas();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscalao(\AppBundle\Entity\Escalao $escalao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscalao', [$escalao]);

        return parent::setEscalao($escalao);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscalao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscalao', []);

        return parent::getEscalao();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpoca(\AppBundle\Entity\Epoca $epoca = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpoca', [$epoca]);

        return parent::setEpoca($epoca);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpoca()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpoca', []);

        return parent::getEpoca();
    }

    /**
     * {@inheritDoc}
     */
    public function addClube(\AppBundle\Entity\Clube $clube)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addClube', [$clube]);

        return parent::addClube($clube);
    }

    /**
     * {@inheritDoc}
     */
    public function removeClube(\AppBundle\Entity\Clube $clube)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeClube', [$clube]);

        return parent::removeClube($clube);
    }

    /**
     * {@inheritDoc}
     */
    public function getClubes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClubes', []);

        return parent::getClubes();
    }

    /**
     * {@inheritDoc}
     */
    public function setJornadas(\AppBundle\Entity\Jornada $jornadas = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJornadas', [$jornadas]);

        return parent::setJornadas($jornadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getJornadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJornadas', []);

        return parent::getJornadas();
    }

    /**
     * {@inheritDoc}
     */
    public function addJornada(\AppBundle\Entity\Jornada $jornada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJornada', [$jornada]);

        return parent::addJornada($jornada);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJornada(\AppBundle\Entity\Jornada $jornada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJornada', [$jornada]);

        return parent::removeJornada($jornada);
    }

}
